name: Draft PDF
on:
  push:
    branches:
      - JOSS

jobs:
  paper:
    name: Paper Draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: JOSS/paper.md

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: JOSS/paper.pdf
