name: Test PProf Package with testthat

on:
  push:
    branches: [ Xiaohan ]
  pull_request:
    branches: [ Xiaohan ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - name: Install dependencies
      run: |
        install.packages("remotes")
        remotes::install_deps(dependencies = TRUE)
    - name: Install testthat
      run: install.packages("testthat")
    - name: Run tests
      run: |
        Rscript -e 'devtools::test()'
