name: Test PProf Package with testthat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-ver:4.3.1

    steps:
    - uses: actions/checkout@v4
    # actions/checkout@v3
    - name: Install dependencies
      run: |
        install2.r --error --deps TRUE remotes
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'
        Rscript -e 'install.packages(c("devtools", "testthat", "RcppArmadillo"))'
    - name: Run tests
      run: |
        Rscript -e 'devtools::test()'
